name: Daily Stock Fetch

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Clean old data files (except .git/.github)
      - name: Remove old CSV/JSON files
        run: |
          find . -type f \( -name '*.csv' -o -name '*.json' \) \
          ! -path './.git/*' ! -path './.github/*' -delete

      # 4. Install dependencies
      - name: Install dependencies
        working-directory: ./
        run: npm install

      # 5. Run your stock fetch script
      - name: Fetch stock data
        working-directory: ./
        run: node fetch_stocks_all_exchanges.mjs

      # 6. Commit and push changes if there are any
      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update stock data"
            git push
          else
            echo "No changes to commit"
          fi
